classdef colorful < audioPlugin
	properties
		bandWidth = "1/12 octave";
		A0 = 55;	C1 = 65.406;	D1 = 73.416;	E1 = 82.407;	G1 = 97.999;
		A1 = 110;	C2 = 130.813;	D2 = 146.832;	E2 = 164.814;	G2 = 195.998;
		A2 = 220;	C3 = 261.626;	D3 = 293.665;	E3 = 329.628;	G3 = 391.995;
		A3 = 440;	C4 = 523.251;	D4 = 587.330;	E4 = 659.255;	G4 = 783.991;
		A4 = 880;	C5 = 1046.502;	D5 = 1174.659;	E5 = 1318.510;	G5 = 1567.982;
		A5 = 1760;	C6 = 2093.005;	D6 = 2349.318;	E6 = 2637.020;	G6 = 3135.963;
		A6 = 3520;	C7 = 4186.009;	D7 = 4698.636;	E7 = 5274.041;	G7 = 6271.927;
		A7 = 7040;	C8 = 8372.018;	D8 = 9397.272;	E8 = 10548.082;	G8 = 12543.854;
		lowGaindB 	= 0;
		midGaindB 	= 0;
		highGaindB	= 0;
	end

	properties (Access = private)
		octFiltA0;	octFiltC1;	octFiltD1;	octFiltE1;	octFiltG1;
		octFiltA1;	octFiltC2;	octFiltD2;	octFiltE2;	octFiltG2;
		octFiltA2;	octFiltC3;	octFiltD3;	octFiltE3;	octFiltG3;
		octFiltA3;	octFiltC4;	octFiltD4;	octFiltE4;	octFiltG4;
		octFiltA4;	octFiltC5;	octFiltD5;	octFiltE5;	octFiltG5;
		octFiltA5;	octFiltC6;	octFiltD6;	octFiltE6;	octFiltG6;
		octFiltA6;	octFiltC7;	octFiltD7;	octFiltE7;	octFiltG7;
		octFiltA7;	octFiltC8;	octFiltD8;	octFiltE8;	octFiltG8;
	end

	properties(Constant)
		PluginInterface = audioPluginInterface( ...
            audioPluginParameter('lowGaindB', ...
				'DisplayName','Low', 'Label','dB', 'Mapping',{'pow', 1/2, -20, 6}, 'Layout',[2,1], 'DisplayNameLocation','above', 'Style','rotaryknob'), ...
			audioPluginParameter('midGaindB', ...
				'DisplayName','Mid', 'Label','dB', 'Mapping',{'pow', 1/2, -20, 6}, 'Layout',[2,2], 'DisplayNameLocation','above', 'Style','rotaryknob'), ...
			audioPluginParameter('highGaindB', ...
				'DisplayName','High', 'Label','dB', 'Mapping',{'pow', 1/2, -20, 6}, 'Layout',[2,3], 'DisplayNameLocation','above', 'Style','rotaryknob'), ...
			audioPluginGridLayout( ...
				'RowHeight',[15,100,15], ...
				'ColumnWidth',[100,100,100]), ...
            'BackgroundColor',[33/255,33/255,33/255]);
		N = 8;
	end

	methods
		function plugin = colorful
			plugin.octFiltA0 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A0, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC1 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C1, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD1 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D1, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE1 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E1, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG1 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G1, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA1 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A1, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC2 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C2, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD2 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D2, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE2 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E2, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG2 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G2, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA2 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A2, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC3 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C3, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD3 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D3, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE3 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E3, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG3 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G3, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA3 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A3, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC4 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C4, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD4 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D4, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE4 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E4, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG4 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G4, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA4 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A4, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC5 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C5, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD5 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D5, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE5 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E5, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG5 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G5, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA5 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A5, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC6 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C6, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD6 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D6, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE6 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E6, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG6 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G6, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA6 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A6, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC7 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C7, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD7 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D7, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE7 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E7, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG7 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G7, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltA7 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.A7, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltC8 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.C8, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltD8 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.D8, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltE8 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.E8, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));
			plugin.octFiltG8 = octaveFilter('FilterOrder',plugin.N, ...
				'CenterFrequency',plugin.G8, 'Bandwidth',plugin.bandWidth, 'SampleRate',getSampleRate(plugin));	
		end

		function out = process(plugin, in)

			low = 	plugin.octFiltA0(in) + plugin.octFiltC1(in) + plugin.octFiltD1(in) + plugin.octFiltE1(in) + plugin.octFiltG1(in);
			
			mid = 	plugin.octFiltA1(in) + plugin.octFiltC2(in) + plugin.octFiltD2(in) + plugin.octFiltE2(in) + plugin.octFiltG2(in) + ...
					plugin.octFiltA2(in) + plugin.octFiltC3(in) + plugin.octFiltD3(in) + plugin.octFiltE3(in) + plugin.octFiltG3(in) + ...
					plugin.octFiltA3(in) + plugin.octFiltC4(in) + plugin.octFiltD4(in) + plugin.octFiltE4(in) + plugin.octFiltG4(in) + ...
					plugin.octFiltA4(in) + plugin.octFiltC5(in) + plugin.octFiltD5(in) + plugin.octFiltE5(in) + plugin.octFiltG5(in) + ...
					plugin.octFiltA5(in);

			high = 	plugin.octFiltC6(in) + plugin.octFiltD6(in) + plugin.octFiltE6(in) + plugin.octFiltG6(in) + ...
					plugin.octFiltA6(in) + plugin.octFiltC7(in) + plugin.octFiltD7(in) + plugin.octFiltE7(in) + plugin.octFiltG7(in) + ...
					plugin.octFiltA7(in) + plugin.octFiltC8(in) + plugin.octFiltD8(in) + plugin.octFiltE8(in) + plugin.octFiltG8(in);

			low_gain	= 10^(plugin.lowGaindB/20);
			mid_gain 	= 10^(plugin.midGaindB/20);
			high_gain 	= 10^(plugin.highGaindB/20);
			low_result	= low * low_gain;
			mid_result 	= mid * mid_gain;
			high_result = high * high_gain;
							
			out = low_result + mid_result + high_result;

		end
	end

end